### ISSUE TITLE
You can't escape " in strings

### ISSUE THREAD

**Issue by ghost** [judofyr/forter#1]
Please add a way to escape quotes in strings, I'm trying to write a quine, thanks.

**Comment by judofyr** [comment]
Wow. I had no idea someone actually used this implementation. Now that I look back at it I want to re-implement everything.

I'm a bit busy at the moment so I probably won't be able to fix this very soon :(

**Comment by ghost** [comment]
This implementation is actually being used by the TIO interpreter: https://tio.run/nexus/forte, so I know several people who use it. If you have time, can you also fix `2LET2=2+1`? It should go into an infinite loop, but instead it just ends: https://tio.run/nexus/forte#@28UEOTpF6KUlp@vZOXjGmJka6Rt@P8/AA

**Comment by judofyr** [comment]
Can you try the new implementation I just pushed? Strings can be escaped with backslash.

**Comment by judofyr** [comment]
https://tio.run/nexus/forte#@29oEBDk6ReioJSRmpOTH6NUnl@Uk6LEZWTg6ufy/z8A
